language: go
go:
- 1.9
env:
  global:
  - ARTIFACTS_BUCKET=jlevasseur-artifact-storage
  - secure: tLoKG5IThCu9skAUeMgxLGeKkYfY19y7QhnpVffIit/KNVOeFgk8rwbJZVJveUyuVvTHv1d4wzytJk76wB5v4dV8pI016I2BGbGjSAy3i3/EHB9WHZIFRw+/zvIcRXOyKg3ltamKsbm66aXwkEeZKKv8r1hK4YR+5UHhMv5DlxBHUGYg+gSGOT/Fph2+mD6I3E+RikhJZVgmpy+GQMtYZMH+PQ1Uc2peYWJ62IOFY0h5cMUgpxWfjABgYJRj65uuIPIBNgiVutrbxljbR1zTEnfBnqZ/rHwP1+MFG627tRaweH52RPKE5GCgD2uk2axDbUvxN+ZTEaiMuRhaUFZfq5p8y7sIou6CVcIbLNEFqVEobcehWgGxFcl/UK0762M7vWk6pqnbEYNjngOJVjfyyrfKo/JFS0Vv4FU97q0IC2dxpl0Mn+KeY4J3uutE9mAAH9sVNCpg6rf01GNfRvDBEQKhqAsBcUvbqUvnZfWA+FTepCg2CyIDYk6LNe+RtRtGFUXe6JFqSyHBLaET70MW1rktVu/2j7H/u6mzQlDoknCOQvpMBJXcroRd7mfyJP0s/xBPVm0wh1kgTy4GAT1nkirqxTr15za55pt04PHBj4mGcLl87gx4VSMe+m4cSGHLOqhENNMVoH9ssQD8nqhDEtQW0l4EeqZMsmRBBUpJZUE=
  - secure: DxuajakaD5FkjCobmatHrrRUd1YHw/rVp7T51P12nEKjnIvt90K60zW5uLw4PbYJSj3SbNaH4sC1goQ92Unp0+mteIR5uOhdpZyLurCV69WDtxS4i4pQ4/RX7okVlar5XhwMvnldOCjB7ZmUSKEgl81QzpQgy6xZV2iymOqcemRSbKZilsbUvUQup7xybSxfXSRy0zR/8YSgtz4dhk8rNZ6Kin79822Jx1SyNNLYTyY4OaJfSHYFZ9flS8szw3pUX9etrh2zl+xBrrAIsnq/j0JLHnpIheYhYl3oPO8lQ+w0AAJ2RtluPaVxImvzWbATkoA9u//Az02RdIQm2RlbDBM20uV6ADqnI62xgb2JlPPXKjBH8ddAhGN2mR5LzTGQGYphItb+znEawO5PgpUuHuANDtRSpCTuriqz5cZuxQbGq0E8ugy5u2UumqnRHXVZpo0ViWnbD5ue/GpBsysiqCsxg4VQg3eGUMp7TQnDgUDXB3moi5Z5NZo50A4WuI/h7l/gKpClzcCzY8aBLqNPRnNpCiI7cQUuITYrQOpByvycXQcRM1u5kXd+tSpHaRG4iM43NVLnkcam5NejQucDIxVVPQyLitTzjd7jYijyo1xaFp0Mv0eeME0z3W8gx4XjcsVpG6Q5FQlpE9qnQbTe2ihOAwGq3PTAQM+m6VGoYA4=
  - secure: u+Z94hYj6RJGlTcWbrQyaN4gqZJt5ce+uXcqrCvAW6zGoIbEEvig9s+kIk5uoFgR8BAJl5Hm+TFVnUi3pTtkvD94mllpEv4OIU8blOw4eWuRDj5BVHYqxYkN+cOtwST/3Fxsr5mpgBDi4Z256N8xiSU//DRWXK02rHg/+xMLvuc4TvJINtkhKIgNEsywbowQHmx0iwW9+6Sa/a5xLnLzQ0rzqV8lpIdLE11mzkGJ13zZbZvNSMkwAOxzSIHKqMd1hLuYVxyIoli/oThKW2+gWhKnuQm8MEJY+Z0LgHAgfnj7HXhOuh9DqOFwp0qPlf8pwR51R+cmbOusYoJbxrZhdKdTHAc3k4vTI5Td2ZYVwnTckTeInSoabdb9JI1i4PQWllarEx1N37NEXE2csRNxgcEEq9JXB3tI3RMBrajEuP3oz2Bm7FZmxP/XC+iD/k1UvvdRxyAHNvHt+YCPU3A+ONLPlPdAxAqUl8HHXs99uLkNhyL8Z7E421seMPmXbPyH/8hbHKxf4VbXlOZsGOse5uSSIqf6Xn9B9R1HeCZZ223IwVvCrq1FOvsh4rC6Du5fTL8SDR0wI06YIWJaaeyUvilM3sIHYleZEfEweHVpvGYoyNr3nbnQFehA4jnXIhFLviifQjaoMOtpw+0l8LHDo66xjd+nDE4yEFYemQd4P8g= #AWS_ACCOUNT_NUMBER
before_install:
- go get -u golang.org/x/lint/golint
jobs:
  include:
  - stage: lint & go build
    script:
    - go version
    - "$GOPATH/bin/golint ."
    - go build
  - stage: docker build & push
    script:
    - docker version
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - eval $(aws ecr get-login --no-include-email | sed 's|https://||')
    - docker build -t software_version_watcher .
    - docker tag software_version_watcher:latest 205942832418.dkr.ecr.us-east-1.amazonaws.com/software_version_watcher:latest
    - docker push 205942832418.dkr.ecr.us-east-1.amazonaws.com/software_version_watcher:latest
